import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Category from "@/components/category";
import Filter from "@/components/filter";
import Bid from "@/components/bid";
import Banner from "@/components/banner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>NFTHUB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black h-fit p-6 mx-auto bg-[url('/backgroundfull.png')] bg-no-repeat bg-center bg-cover ">
        <div className="flex flex-col max-w-[90rem] mx-auto gap-10">
          <Navbar />
          <Banner />
          <Bid />
          <Filter />
          <Category />
          <Footer />
        </div>
      </main>
    </>
  );
}
